language: python
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- "nightly"
install:
- pip install --upgrade pip>=8.0.0
- pip --version
# Temporary for until we have a setup script.
- pip install pathlib2 toml localimport appdirs click distlib hammock jsonschema requests
script:
- python -m nodepy.main ./nodepy-pm
