language: python
python:
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- "nightly"
install:
- pip install --upgrade pip>=8.0.0
- pip install . -v
script:
- node.py --version
- export PATH=${PATH}:$(node.py ppym bin --global)
- ppym
