site_name: 'Node.py Documentation'
docs_dir: 'source'
theme: 'bootstrap'
markdown_extensions:
- codehilite
- smarty
pages:
- Home: index.md
- Changelog: changelog.md
- Troubleshooting: troubleshooting.md
- nodepy: nodepy.md
- nodepy-pm:
  - package.json: nodepy-pm/manifest.md
  - CLI: nodepy-pm/cli.md
